[package]
name = "gaudip"
version = "0.1.0"
edition = "2021"

[workspace]
members = [
    "crates/rope",
]

[workspace.package]
edition = "2024"

[workspace.dependencies]
rand = "0.9.2"
rand_chacha = "0.9.0"
slab = "0.4.11"

roperig = { path = "crates/rope" }

[dependencies]
glib = "0.21"
gtk = { version = "0.10.1", package = "gtk4", features = ["v4_14"] }

async-channel = "2.5.0"
env_logger = "0.11.8"
log = "0.4"
tokio = { version = "1", features = ["full"] }

roperig = { workspace = true }

[profile.dev]
split-debuginfo = "unpacked"
