// This file contains all the IPC endpoints, specified as FlatBuffers rpc_service.
// For rpc_service, FlatBuffers uses gRPC, which is a bit heavyweight, and it
// does not support Rust for now. So, instead of using gRPC, we use a rather simple
// IPC schema, and this file is for the user to generate such IPC code themselves.
//
// # File Format
// To ease the burden of code-generation, this file promises that, all IPC endpoints
// are defined by lines strictly matching the following regular expression:
//
//     /^  (\w+)\((\w+)\):(\w+) \(id: (\d+), dir: "(c2s|s2c|2way)"\);$/
//
// Or, using named capture groups:
//
//     /^  (?<endpoint>\w+)\((?<request>\w+)\):(?<response>\w+) \(id: (?<id>\d+), dir: "(?<dir>c2s|s2c|2way)"\);$/
//
// # IPC Schema
//
// - `(packet_id: u32)(endpoint_id: u32)(length: u32)(_: u32)(packet_content: [u8; length])`
//
// - The byte-order is native.
// - `packet_id`: Auto-incrementing packet ID, used for request tracking and synchronization.
// - `endpoint_id`: As is specified by this file, non-zero.
//   - `endpoint_id = 0`: A response packet for a request packet with the same `packet_id`.
//   - `endpoint_id == 0xFFFF_FFFF`: Error response packet.
// - `length`: The length in bytes of `packet_content`.
// - `_`: Reserved. We might afford a bit of CRC checking?
// - `packet_content`: FlatBuffers-encoded content, as is specified in relevant schema files.
//
// The response is encoded in exactly the same format, except that its `endpoint_id` is zero.

include "registration.fbs";
include "buffer.fbs";

namespace party.iroiro.juicemacs.ipc;

/// Request direction, "c2s", "s2c", or "2way".
attribute dir;

rpc_service EditorServer {
  Register(RegistrationRequest):RegistrationResponse (id: 1, dir: "c2s");
  Ping(PingRequest):PingResponse (id: 2, dir: "2way");
}
