[package]
name = "roperig"
license = "MIT"
version = "0.1.0"
authors = ["Sevag Hanssian <sevag.hanssian@gmail.com>"]
edition = "2018"

[dependencies]
slab = "0.4.11"

[dev-dependencies]
rand = "0.9.2"
rand_chacha = "0.9.0"